image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - build
  - publish
  - scan
  - pages

include:
  # Run python jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'
  # Include documentation
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
  # Run finalizer, inc. ci-metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# override default images with image having cmake installed
python-lint:
  image:artefact.skao.int/ska-cicd-k8s-tools-build-deploy:0.8.6
python-test:
  image:artefact.skao.int/ska-cicd-k8s-tools-build-deploy:0.8.6
